### ISSUE TITLE
Lidatube not saving files

### ISSUE THREAD

**Issue by tyrellm04** [TheWicklowWolf/LidaTube#48]
Hello,

I'm having some trouble getting Lidatube to actually save files. 

Below is the Lidatube compose service:
```  
  lidatube:
    image: thewicklowwolf/lidatube:latest
    container_name: lidatube
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=3002
      - PGID=3002
      - lidarr_address=http://10.10.210.12:80
      - lidarr_api_key=749c4f7498be4719a02b1a5099f4ac33
      - preferred_codec=aac
      - sync_schedule=0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23
      - thread_limit=20
    volumes:
      - ./lidatube/data:/lidatube/config
      - ./firefox/config/Downloads:/config
      - /mnt/DataPool/jellyfin/Music:/lidatube/download
      - /etc/localtime:/etc/localtime:ro
```

When I check the lidatube logs, it says it's successfully downloading:
```
Searching for: AFI - 336
Searching for Whole Album: AFI - 336
No matching album for: AFI - 336
Searching for individual Tracks: AFI - 336
Links found for all Tracks of: AFI - 336
Valid link count of 2 for: AFI - 336
Starting Download of: Now The World
Downloaded   0.0% of   14.03MiB at  408.88KiB/s
Downloaded   0.0% of   14.03MiB at    1.01MiB/s
Downloaded   0.0% of   14.03MiB at    2.13MiB/s
Downloaded   0.1% of   14.03MiB at    4.16MiB/s
Downloaded   0.2% of   14.03MiB at    5.59MiB/s
Downloaded   0.4% of   14.03MiB at    2.46MiB/s
Downloaded   0.9% of   14.03MiB at    1.48MiB/s
Downloaded   1.8% of   14.03MiB at    2.91MiB/s
Downloaded   3.6% of   14.03MiB at    4.41MiB/s
Downloaded   7.1% of   14.03MiB at    4.22MiB/s
Downloaded  14.2% of   14.03MiB at    5.58MiB/s
Downloaded  28.5% of   14.03MiB at    6.88MiB/s
Downloaded  57.0% of   14.03MiB at    7.73MiB/s
Downloaded  70.7% of   14.03MiB at    7.54MiB/s
Downloaded  70.7% of   14.03MiB at  477.60KiB/s
Downloaded  70.7% of   14.03MiB at    1.17MiB/s
Downloaded  70.8% of   14.03MiB at    2.50MiB/s
Downloaded  70.8% of   14.03MiB at    4.93MiB/s
Downloaded  70.9% of   14.03MiB at    5.00MiB/s
Downloaded  71.2% of   14.03MiB at    5.94MiB/s
Downloaded  71.6% of   14.03MiB at    1.78MiB/s
Downloaded  72.5% of   14.03MiB at    2.80MiB/s
Downloaded  74.3% of   14.03MiB at    2.77MiB/s
Downloaded  77.8% of   14.03MiB at    4.03MiB/s
Downloaded  85.0% of   14.03MiB at    4.81MiB/s
Downloaded  99.2% of   14.03MiB at    5.15MiB/s
Downloaded 100.0% of   14.03MiB at    5.27MiB/s
Download complete
Replacing existing file "/lidatube/downloads/AFI/336 (2002)/AFI - 336 - 01 - Now The World.m4a"
DL Complete : https://www.youtube.com/watch?v=d6Fxh7a1Th8
Metadata added for downloads/AFI/336 (2002)/AFI - 336 - 01 - Now The World.aac
```

Then when I do a docker exec command into the lidatube container to show me all of the directories in the "/lidatube/download/AFI" folder to find the "336 (2002)" directory it is not present:
```
sudo docker exec -it lidatube ls -l /lidatube/download/AFI
total 83
drwxrwxrwx    2 3002     3002            16 Jan  6 08:22 AFI (The Blood Album) (2017)
drwxrwxrwx    2 3002     3002            13 Jan  6 08:22 Bodies (2021)
drwxrwxrwx    2 3002     3002            15 Jan  6 12:40 Burials (2013)
```

When I do the same ls -l command on the mapped host directory "/mnt/DataPool/jellyfin/Music/AFI" it's not listed either.
```
sudo ls -l /mnt/DataPool/jellyfin/Music/AFI
total 83
drwxrwxrwx 2 radarr radarr 16 Jan  6 08:22 'AFI (The Blood Album) (2017)'
drwxrwxrwx 2 radarr radarr 13 Jan  6 08:22 'Bodies (2021)'
drwxrwxrwx 2 radarr radarr 15 Jan  6 12:40 'Burials (2013)'
```

I also verified (though I was certain) that the radarr user is also PUID PGID 3002, but it is.
```
sudo id radarr
uid=3002(radarr) gid=3002(radarr) groups=3002(radarr),545(builtin_users)
```
